version: "3.8"

services:
  web:
    build: .
    ports: ["3000:3000"]
    env_file: .env
    environment:
      APP_PASSWORD: ${APP_PASSWORD:-cheese}
      APP_QB_URL: ${APP_QB_URL:-http://qbittorrent:8080}
      APP_QB_USERNAME: ${APP_QB_USERNAME:-admin}
      APP_QB_PASSWORD: ${APP_QB_PASSWORD:-adminadmin}
      APP_MAM_USER_AGENT: ${APP_MAM_USER_AGENT:-Scurry/2.0 (+contact)}
    restart: unless-stopped
